export enum DISPOSITION_SEARCH_MODAL_NAMES {
	CREATE_SEARCH = 'CREATE_SEARCH',
	UNSAVED_CHANGES_CREATE_SEARCH = 'UNSAVED_CHANGES_CREATE_SEARCH',
	EDIT_SEARCH = 'EDIT_SEARCH',
	UNSAVED_CHANGES_EDIT_SEARCH = 'UNSAVED_CHANGES_EDIT_SEARCH',
	DELETE_SEARCH = 'DELETE_SEARCH',
	DELETE_SEARCH_SNAPSHOT = 'DELETE_SEARCH_SNAPSHOT',
}

export enum AUTH_PROVIDER_MODAL_NAMES {
	EDIT_AUTH_PROVIDER = 'EDIT_AUTH_PROVIDER',
	UNSAVED_CHANGES_EDIT_AUTH_PROVIDER = 'UNSAVED_CHANGES_EDIT_AUTH_PROVIDER',
	CREATE_AUTH_PROVIDER = 'CREATE_AUTH_PROVIDER',
	UNSAVED_CHANGES_CREATE_AUTH_PROVIDER = 'UNSAVED_CHANGES_CREATE_AUTH_PROVIDER',
	DELETE_PROVIDER = 'DELETE_AUTH_PROVIDER',
}

export enum DATA_SYNC_MODAL_NAMES {
	CREATE_DATA_SYNC_PROVIDER = 'CREATE_DATA_SYNC_PROVIDER',
	UNSAVED_CHANGES_CREATE_DATA_SYNC_PROVIDER = 'UNSAVED_CHANGES_CREATE_DATA_SYNC_PROVIDER',
	UPDATE_DATA_SYNC_PROVIDER = 'UPDATE_DATA_SYNC_PROVIDER',
	UNSAVED_CHANGES_UPDATE_DATA_SYNC_PROVIDER = 'UNSAVED_CHANGES_UPDATE_DATA_SYNC_PROVIDER',
	DELETE_PROVIDER = 'DELET_DATA_SYNC_PROVIDER',
}

export const IMAGE_CROPPER = 'IMAGE_CROPPER';
export const MANAGE_TABLE_COLUMNS = 'MANAGE_TABLE_COLUMNS';
export const PROFILE_SETTINGS = 'PROFILE_SETTINGS';
export const UNSAVED_PROFILE_SETTINGS = 'UNSAVED_PROFILE_SETTINGS';
